//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpiHeroesInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Sexe { get; set; }
        public int ComicId { get; set; }
    
        public virtual Comic Comic { get; set; }
    }
}
